AWSTemplateFormatVersion: "2010-09-09"

Description: >
  Stack used to deploy EC2 for testing purposes

Parameters:
  AmiId:
    Type: String
    Description: Ami id to use
    # Default: ami-0484cefb8f48dafe8 # DeepLearning
    Default: ami-009d6802948d06e52

  TypeOfInstance:
    Type: String
    Description: Type of instance
    Default: t2.micro
    # Default: g2.2xlarge # Deeplearning

  KeyPair:
    Type: String
    Description: Key pair to access instance via ssh
    Default: aveselov-useast1

Resources:
  NetworkInterface:
    Type: "AWS::EC2::NetworkInterface"
    Properties:
      Description: Access to Jenkins Master host
      GroupSet: 
        - !ImportValue JenkinsSG
      SubnetId: !ImportValue VpcASubnetB


  EC2:
    Type: "AWS::EC2::Instance"
    Properties:
      # IamInstanceProfile: arn:aws:iam::054305859799:role/Visitor
      ImageId: !Ref AmiId
      InstanceType: !Ref TypeOfInstance
      KeyName: !Ref KeyPair
      NetworkInterfaces:
        - DeviceIndex: 0
          NetworkInterfaceId: !Ref NetworkInterface
      UserData:
        Fn::Base64:
          Fn::Sub:
            - |
              #!/bin/bash -xe
              
              sudo apt install -y python2.7 g++-5 ocl-icd-* opencl-headers ibopenimageio-dev libglew-dev libglfw3-dev
            - {}

  # AssociateEIP:
  #   Type: "AWS::EC2::EIPAssociation"
  #   Properties:
  #     EIP: !ImportValue "EIPVpcA"
  #     InstanceId: !Ref EC2
  #     NetworkInterfaceId: !Ref NetworkInterface

